spring:
  application:
    name: journalize

  # KAFKA CONFIGURATION
  kafka:
    bootstrap-servers: ${KAFKA_HOST}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

    consumer:
      group-id: ${KAFKA_GROUP_JOURNALIZE}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: com.journalize.journalize.dto.user
        spring.json.value.default.type: com.journalize.journalize.dto.user.SentimentData

  # RABBITMQ CONFIGURATION
  rabbitmq:
    addresses: ${RABBITMQ_URL}
    ssl:
      enabled: true

  # AUTO RESTART AND LIVE RELOAD CONFIGURATION
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  # MONGODB CONFIGURATION
  mongodb:
    uri: ${MONGODB_URI}
    database: ${MONGODB_DATABASE}

  data:
    mongodb:
      auto-index-creation: true

    redis:
      url: ${REDIS_URL}

# SERVER CONFIGURATION
server:
  servlet:
    context-path: /api

# JWT CONFIGURATION
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 1 day

# WEATHERSTACK CONFIGURATION
weatherstack:
  api-key: ${WEATHERSTACK_API_KEY}

# BREVO CONFIGURATION
brevo:
  api-key: ${BREVO_API_KEY}
  url: ${BREVO_API_URL}
  domain: ${BREVO_EMAIL_DOMAIN}
  name: ${BREVO_SENDER_NAME}

# KAFKA CUSTOM CONFIGURATION
kafka:
  enabled: ${KAFKA_ENABLED:false}

# RABBITMQ CUSTOM CONFIGURATION
rabbitmq:
  exchange: journalize.exchange
  queue: weekly.sentiment.queue
  routing-key: weekly.sentiment