spring:
  application:
    name: journalize

  # AUTO RESTART AND LIVE RELOAD CONFIGURATION
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  # MONGODB CONFIGURATION
  mongodb:
    uri: ${MONGODB_URI}
    database: ${MONGODB_DATABASE}

  # ENABLE AUTO-INDEX CREATION FOR MONGODB
  data:
    mongodb:
      auto-index-creation: true

# SERVER CONFIGURATION
server:
  servlet:
    context-path: /api      

# JWT CONFIGURATION
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 1 day in milliseconds   

# WEATHERSTACK CONFIGURATION
weatherstack:
  api-key: ${WEATHERSTACK_API_KEY}

# BREVO CONFIGURATION
brevo:
  api-key: ${BREVO_API_KEY}
  url: ${BREVO_API_URL}
  domain: ${BREVO_EMAIL_DOMAIN}
  name: ${BREVO_SENDER_NAME}          